import { createB2BackgroundSceneDemoState, type BackgroundLayer, type SpriteBackgroundLayer } from "../render/webgl/bg/layers/BackgroundLayerTypes";
import type { BackgroundChunk, BackgroundScene } from "../render/webgl/bg/layers/BackgroundSceneTypes";

export type LayerOwner = { kind: "global" } | { kind: "chunk"; chunkId: string };
export const cloneScene = (scene: BackgroundScene): BackgroundScene => JSON.parse(JSON.stringify(scene)) as BackgroundScene;
export function createDemoScene(): BackgroundScene { const source = createB2BackgroundSceneDemoState().source; return cloneScene(source?.kind === "scene" ? source.scene : { id: "empty", globalLayers: [], chunks: [] }); }
function uniqueId(base: string, used: Set<string>): string { let id = base.replace(/[^a-zA-Z0-9_-]+/g, "-").replace(/^-+|-+$/g, "") || "item"; if (!used.has(id)) return id; let n = 2; while (used.has(`${id}-${n}`)) n++; return `${id}-${n}`; }
export function layerOwner(scene: BackgroundScene, owner: LayerOwner): BackgroundLayer[] { return owner.kind === "global" ? scene.globalLayers : scene.chunks.find(c => c.id === owner.chunkId)?.layers ?? []; }
function withOwner(scene: BackgroundScene, owner: LayerOwner, layers: BackgroundLayer[]): BackgroundScene { return owner.kind === "global" ? { ...scene, globalLayers: layers } : { ...scene, chunks: scene.chunks.map(c => c.id === owner.chunkId ? { ...c, layers } : c) }; }
export function addChunk(scene: BackgroundScene): BackgroundScene { const used = new Set(scene.chunks.map(c=>c.id)); const lastEnd = scene.chunks.reduce((m,c)=>Math.max(m,c.startX+c.length),0); return { ...scene, chunks: [...scene.chunks, { id: uniqueId("chunk", used), startX: lastEnd, length: 720, layers: [] }] }; }
export function duplicateChunk(scene: BackgroundScene, chunkId: string): BackgroundScene { const c = scene.chunks.find(x=>x.id===chunkId); if (!c) return scene; const used = new Set(scene.chunks.map(x=>x.id)); const copy = cloneScene({ id:"x", globalLayers:[], chunks:[c] }).chunks[0]; copy.id = uniqueId(`${c.id}-copy`, used); copy.startX = c.startX + c.length; return { ...scene, chunks: [...scene.chunks, copy] }; }
export function deleteChunk(scene: BackgroundScene, chunkId: string): BackgroundScene { return { ...scene, chunks: scene.chunks.filter(c=>c.id!==chunkId) }; }
export function moveChunk(scene: BackgroundScene, chunkId: string, dir: -1|1): BackgroundScene { const chunks = scene.chunks.slice(); const i = chunks.findIndex(c=>c.id===chunkId); const j=i+dir; if (i<0||j<0||j>=chunks.length) return scene; [chunks[i],chunks[j]]=[chunks[j],chunks[i]]; return { ...scene, chunks }; }
export function updateChunk(scene: BackgroundScene, chunkId: string, patch: Partial<Pick<BackgroundChunk,"id"|"startX"|"length">>): BackgroundScene { return { ...scene, chunks: scene.chunks.map(c=>c.id===chunkId ? { ...c, ...patch } : c) }; }
export function createSpriteLayer(id="sprite-layer"): SpriteBackgroundLayer { return { id, kind: "sprite", enabled: true, texture: { url: "/assets/bg/b1_pixel_stars.svg", filtering: "nearest" }, opacity: 1, blend: "normal", parallax: { x: 0.5, y: 0 }, offset: { x: 0, y: 0 }, repeat: { x: true, y: true } }; }
export function addLayer(scene: BackgroundScene, owner: LayerOwner): BackgroundScene { const layers = layerOwner(scene, owner); const id = uniqueId("sprite-layer", new Set(layers.map(l=>l.id))); return withOwner(scene, owner, [...layers, createSpriteLayer(id)]); }
export function duplicateLayer(scene: BackgroundScene, owner: LayerOwner, layerId: string): BackgroundScene { const layers = layerOwner(scene, owner); const layer = layers.find(l=>l.id===layerId); if (!layer) return scene; const copy = JSON.parse(JSON.stringify(layer)) as BackgroundLayer; copy.id = uniqueId(`${layer.id}-copy`, new Set(layers.map(l=>l.id))); return withOwner(scene, owner, [...layers, copy]); }
export function deleteLayer(scene: BackgroundScene, owner: LayerOwner, layerId: string): BackgroundScene { return withOwner(scene, owner, layerOwner(scene, owner).filter(l=>l.id!==layerId)); }
export function moveLayer(scene: BackgroundScene, owner: LayerOwner, layerId: string, dir: -1|1): BackgroundScene { const layers = layerOwner(scene, owner).slice(); const i = layers.findIndex(l=>l.id===layerId), j=i+dir; if (i<0||j<0||j>=layers.length) return scene; [layers[i],layers[j]]=[layers[j],layers[i]]; return withOwner(scene, owner, layers); }
export function updateLayer(scene: BackgroundScene, owner: LayerOwner, layerId: string, patcher: (layer: BackgroundLayer)=>BackgroundLayer): BackgroundScene { return withOwner(scene, owner, layerOwner(scene, owner).map(l=>l.id===layerId ? patcher(JSON.parse(JSON.stringify(l))) : l)); }
