import { createB2BackgroundSceneDemoState, type BackgroundLayer, type SpriteBackgroundLayer } from "../render/webgl/bg/layers/BackgroundLayerTypes";
import type { BackgroundChunk, BackgroundScene } from "../render/webgl/bg/layers/BackgroundSceneTypes";
import type { BackgroundMarker, BackgroundMarkerAction } from "../render/webgl/bg/layers/BackgroundMarkerTypes";

export type LayerOwner = { kind: "global" } | { kind: "chunk"; chunkId: string };
export const cloneScene = (scene: BackgroundScene): BackgroundScene => JSON.parse(JSON.stringify(scene)) as BackgroundScene;
export function createDemoScene(): BackgroundScene { const source = createB2BackgroundSceneDemoState().source; return cloneScene(source?.kind === "scene" ? source.scene : { id: "empty", globalLayers: [], chunks: [] }); }
function uniqueId(base: string, used: Set<string>): string { let id = base.replace(/[^a-zA-Z0-9_-]+/g, "-").replace(/^-+|-+$/g, "") || "item"; if (!used.has(id)) return id; let n = 2; while (used.has(`${id}-${n}`)) n++; return `${id}-${n}`; }
export function layerOwner(scene: BackgroundScene, owner: LayerOwner): BackgroundLayer[] { return owner.kind === "global" ? scene.globalLayers : scene.chunks.find(c => c.id === owner.chunkId)?.layers ?? []; }
function withOwner(scene: BackgroundScene, owner: LayerOwner, layers: BackgroundLayer[]): BackgroundScene { return owner.kind === "global" ? { ...scene, globalLayers: layers } : { ...scene, chunks: scene.chunks.map(c => c.id === owner.chunkId ? { ...c, layers } : c) }; }
export function addChunk(scene: BackgroundScene): BackgroundScene { const used = new Set(scene.chunks.map(c=>c.id)); const lastEnd = scene.chunks.reduce((m,c)=>Math.max(m,c.startX+c.length),0); return { ...scene, chunks: [...scene.chunks, { id: uniqueId("chunk", used), startX: lastEnd, length: 720, layers: [] }] }; }
export function duplicateChunk(scene: BackgroundScene, chunkId: string): BackgroundScene { const c = scene.chunks.find(x=>x.id===chunkId); if (!c) return scene; const used = new Set(scene.chunks.map(x=>x.id)); const copy = cloneScene({ id:"x", globalLayers:[], chunks:[c] }).chunks[0]; copy.id = uniqueId(`${c.id}-copy`, used); copy.startX = c.startX + c.length; return { ...scene, chunks: [...scene.chunks, copy] }; }
export function deleteChunk(scene: BackgroundScene, chunkId: string): BackgroundScene { return { ...scene, chunks: scene.chunks.filter(c=>c.id!==chunkId) }; }
export function moveChunk(scene: BackgroundScene, chunkId: string, dir: -1|1): BackgroundScene { const chunks = scene.chunks.slice(); const i = chunks.findIndex(c=>c.id===chunkId); const j=i+dir; if (i<0||j<0||j>=chunks.length) return scene; [chunks[i],chunks[j]]=[chunks[j],chunks[i]]; return { ...scene, chunks }; }
export function updateChunk(scene: BackgroundScene, chunkId: string, patch: Partial<Pick<BackgroundChunk,"id"|"startX"|"length">>): BackgroundScene { return { ...scene, chunks: scene.chunks.map(c=>c.id===chunkId ? { ...c, ...patch } : c) }; }
export function createSpriteLayer(id="sprite-layer"): SpriteBackgroundLayer { return { id, kind: "sprite", enabled: true, texture: { url: "/assets/bg/b1_pixel_stars.svg", filtering: "nearest" }, opacity: 1, blend: "normal", parallax: { x: 0.5, y: 0 }, offset: { x: 0, y: 0 }, repeat: { x: true, y: true } }; }
export function addLayer(scene: BackgroundScene, owner: LayerOwner): BackgroundScene { const layers = layerOwner(scene, owner); const id = uniqueId("sprite-layer", new Set(layers.map(l=>l.id))); return withOwner(scene, owner, [...layers, createSpriteLayer(id)]); }
export function duplicateLayer(scene: BackgroundScene, owner: LayerOwner, layerId: string): BackgroundScene { const layers = layerOwner(scene, owner); const layer = layers.find(l=>l.id===layerId); if (!layer) return scene; const copy = JSON.parse(JSON.stringify(layer)) as BackgroundLayer; copy.id = uniqueId(`${layer.id}-copy`, new Set(layers.map(l=>l.id))); return withOwner(scene, owner, [...layers, copy]); }
export function deleteLayer(scene: BackgroundScene, owner: LayerOwner, layerId: string): BackgroundScene { return withOwner(scene, owner, layerOwner(scene, owner).filter(l=>l.id!==layerId)); }
export function moveLayer(scene: BackgroundScene, owner: LayerOwner, layerId: string, dir: -1|1): BackgroundScene { const layers = layerOwner(scene, owner).slice(); const i = layers.findIndex(l=>l.id===layerId), j=i+dir; if (i<0||j<0||j>=layers.length) return scene; [layers[i],layers[j]]=[layers[j],layers[i]]; return withOwner(scene, owner, layers); }
export function updateLayer(scene: BackgroundScene, owner: LayerOwner, layerId: string, patcher: (layer: BackgroundLayer)=>BackgroundLayer): BackgroundScene { const layers = layerOwner(scene, owner); if (!layers.some(l => l.id === layerId)) return scene; return withOwner(scene, owner, layers.map(l=>l.id===layerId ? patcher(JSON.parse(JSON.stringify(l))) : l)); }

export type PixelSafeMode = "integer" | "fractional";
function maybeRound(v: number, mode: PixelSafeMode): number { return mode === "integer" ? Math.round(v) : v; }
export function updateSelectedSpriteOffset(scene: BackgroundScene, owner: LayerOwner, layerId: string, offset: { x: number; y: number }, mode: PixelSafeMode = "integer"): BackgroundScene {
  return updateLayer(scene, owner, layerId, (layer) => layer.kind === "sprite" ? { ...layer, offset: { x: maybeRound(offset.x, mode), y: maybeRound(offset.y, mode) } } : layer);
}
export function nudgeSpriteLayer(scene: BackgroundScene, owner: LayerOwner, layerId: string, dx: number, dy: number, mode: PixelSafeMode = "integer"): BackgroundScene {
  return updateLayer(scene, owner, layerId, (layer) => layer.kind === "sprite" ? { ...layer, offset: { x: maybeRound(layer.offset.x + dx, mode), y: maybeRound(layer.offset.y + dy, mode) } } : layer);
}
export function roundSpriteOffset(scene: BackgroundScene, owner: LayerOwner, layerId: string): BackgroundScene {
  return updateLayer(scene, owner, layerId, (layer) => layer.kind === "sprite" ? { ...layer, offset: { x: Math.round(layer.offset.x), y: Math.round(layer.offset.y) } } : layer);
}
export function assignAssetToSpriteLayer(scene: BackgroundScene, owner: LayerOwner, layerId: string, url: string): BackgroundScene {
  return updateLayer(scene, owner, layerId, (layer) => layer.kind === "sprite" ? { ...layer, texture: { ...layer.texture, url } } : layer);
}


export type MarkerOwner = { kind: "global" } | { kind: "chunk"; chunkId: string };
export function markerOwner(scene: BackgroundScene, owner: MarkerOwner): BackgroundMarker[] { return owner.kind === "global" ? scene.markers ?? [] : scene.chunks.find(c => c.id === owner.chunkId)?.markers ?? []; }
function withMarkerOwner(scene: BackgroundScene, owner: MarkerOwner, markers: BackgroundMarker[]): BackgroundScene { return owner.kind === "global" ? { ...scene, markers } : { ...scene, chunks: scene.chunks.map(c => c.id === owner.chunkId ? { ...c, markers } : c) }; }
export function createMarker(id = "marker"): BackgroundMarker { return { id, x: 0, enabled: true, once: true, actions: [] }; }
export function addMarker(scene: BackgroundScene, owner: MarkerOwner): BackgroundScene { const markers = markerOwner(scene, owner); return withMarkerOwner(scene, owner, [...markers, createMarker(uniqueId("marker", new Set(markers.map(m => m.id))))]); }
export function duplicateMarker(scene: BackgroundScene, owner: MarkerOwner, markerId: string): BackgroundScene { const markers = markerOwner(scene, owner); const m = markers.find(x => x.id === markerId); if (!m) return scene; const copy = JSON.parse(JSON.stringify(m)) as BackgroundMarker; copy.id = uniqueId(`${m.id}-copy`, new Set(markers.map(x => x.id))); return withMarkerOwner(scene, owner, [...markers, copy]); }
export function deleteMarker(scene: BackgroundScene, owner: MarkerOwner, markerId: string): BackgroundScene { return withMarkerOwner(scene, owner, markerOwner(scene, owner).filter(m => m.id !== markerId)); }
export function moveMarker(scene: BackgroundScene, owner: MarkerOwner, markerId: string, dir: -1|1): BackgroundScene { const markers = markerOwner(scene, owner).slice(); const i = markers.findIndex(m => m.id === markerId), j = i + dir; if (i < 0 || j < 0 || j >= markers.length) return scene; [markers[i], markers[j]] = [markers[j], markers[i]]; return withMarkerOwner(scene, owner, markers); }
export function updateMarker(scene: BackgroundScene, owner: MarkerOwner, markerId: string, patcher: (m: BackgroundMarker) => BackgroundMarker): BackgroundScene { const markers = markerOwner(scene, owner); if (!markers.some(m => m.id === markerId)) return scene; return withMarkerOwner(scene, owner, markers.map(m => m.id === markerId ? patcher(JSON.parse(JSON.stringify(m))) : m)); }
export function toggleMarker(scene: BackgroundScene, owner: MarkerOwner, markerId: string): BackgroundScene { return updateMarker(scene, owner, markerId, m => ({ ...m, enabled: !m.enabled })); }
export function createMarkerAction(kind: BackgroundMarkerAction["kind"] = "set-layer-opacity", layerId = ""): BackgroundMarkerAction { if (kind === "set-layer-enabled") return { kind, layerId, enabled: true }; if (kind === "pulse-layer-opacity") return { kind, layerId, from: 0, to: 1, durationMs: 500 }; if (kind === "emit-environment-event") return { kind, event: "environment-event" }; return { kind, layerId, opacity: 1 }; }
export function addMarkerAction(scene: BackgroundScene, owner: MarkerOwner, markerId: string, action: BackgroundMarkerAction = createMarkerAction()): BackgroundScene { return updateMarker(scene, owner, markerId, m => ({ ...m, actions: [...m.actions, action] })); }
export function duplicateMarkerAction(scene: BackgroundScene, owner: MarkerOwner, markerId: string, index: number): BackgroundScene { return updateMarker(scene, owner, markerId, m => { if (index < 0 || index >= m.actions.length) return m; return { ...m, actions: [...m.actions, JSON.parse(JSON.stringify(m.actions[index]))] }; }); }
export function deleteMarkerAction(scene: BackgroundScene, owner: MarkerOwner, markerId: string, index: number): BackgroundScene { return updateMarker(scene, owner, markerId, m => ({ ...m, actions: m.actions.filter((_, i) => i !== index) })); }
export function moveMarkerAction(scene: BackgroundScene, owner: MarkerOwner, markerId: string, index: number, dir: -1|1): BackgroundScene { return updateMarker(scene, owner, markerId, m => { const actions = m.actions.slice(); const j = index + dir; if (index < 0 || j < 0 || j >= actions.length) return m; [actions[index], actions[j]] = [actions[j], actions[index]]; return { ...m, actions }; }); }
export function updateMarkerAction(scene: BackgroundScene, owner: MarkerOwner, markerId: string, index: number, patcher: (a: BackgroundMarkerAction) => BackgroundMarkerAction): BackgroundScene { return updateMarker(scene, owner, markerId, m => ({ ...m, actions: m.actions.map((a, i) => i === index ? patcher(JSON.parse(JSON.stringify(a))) : a) })); }
