import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createBackgroundV2DesertTestScene } from "../render/bg/v2/BackgroundV2DesertTestScene";
import { clickedTimelineCurrentX, createExactTimelineScale, PIXEL_BGR_TIMELINE_ZOOM_LEVELS, timelineFitZoom, timelinePointerDeltaWorld, worldToTimelinePx } from "./PixelBgrTimeline";
import { projectBackgroundV2Timeline, setV2RoleTracksEnabled, v2RoleVisibility } from "./PixelBgrV2TimelineProjection";

const source = readFileSync(new URL("./PixelBgrLabUI.ts", import.meta.url), "utf8");
const layout = readFileSync(new URL("./PixelBgrDevWorkspaceLayout.ts", import.meta.url), "utf8");
const desert = createBackgroundV2DesertTestScene();
const projection = projectBackgroundV2Timeline(desert);
assert.deepEqual(projection.lanes.map((lane) => lane.label), ["Front", "Near", "Mid", "Far"], "all canonical gutter role labels remain present");
const far = projection.lanes.find(lane => lane.id === "far")!;
assert.deepEqual(far.tracks.map(track => track.id), ["desert-far"], "Far contains only moving Desert content");
assert.equal(v2RoleVisibility(far.tracks), "all", "eye state derives as all enabled");
const mixed = setV2RoleTracksEnabled(desert, ["desert-far"], false);
assert.equal(v2RoleVisibility(projectBackgroundV2Timeline(mixed).lanes.find(lane => lane.id === "far")!.tracks), "none", "single Far track visibility remains authoritative");
const enabled = setV2RoleTracksEnabled(mixed, far.tracks.map(track => track.id), true);
assert.equal(v2RoleVisibility(projectBackgroundV2Timeline(enabled).lanes.find(lane => lane.id === "far")!.tracks), "all", "mixed click policy can enable every represented track");
assert(enabled.tracks.filter(track => track.role === "far").every(track => track.enabled), "mutation writes BackgroundTrack.enabled for every Far track");
assert.equal(mixed.tracks.find(track => track.id === "desert-far")?.enabled, false, "edit writes only the requested Far track");

assert.deepEqual(PIXEL_BGR_TIMELINE_ZOOM_LEVELS, [0.01, 0.015, 0.02, 0.03, 0.05, 0.075, 0.1, 0.15, 0.2, 0.3, 0.5, 0.75, 1, 1.5, 2], "zoom supports fine canonical overview steps");
const scale1 = createExactTimelineScale(0, 1000, 1000, 1);
const scale2 = createExactTimelineScale(0, 1000, 1000, 2);
assert.equal(worldToTimelinePx(400, scale2), worldToTimelinePx(400, scale1) * 2, "zoom feeds the canonical exact scale");
assert.equal(clickedTimelineCurrentX(worldToTimelinePx(400, scale2), 0, scale2), 400, "zoomed seek remains the exact inverse mapping");
assert.equal(timelinePointerDeltaWorld(0, 200, scale2), 100, "zoomed editing uses that same scale authority");
assert.equal(timelineFitZoom(900, 20_000), 0.03, "a non-preset mathematical ratio resolves to the closest fitting preset");
assert.equal(timelineFitZoom(900, 720), 1, "Fit does not enlarge a timeline that already fits");
assert.equal(timelineFitZoom(1, 1_000_000), PIXEL_BGR_TIMELINE_ZOOM_LEVELS[0], "Fit falls back to the smallest preset when no level fully fits");
for (const width of [1, 720, 1_337, 20_000, 1_000_000]) {
  assert(PIXEL_BGR_TIMELINE_ZOOM_LEVELS.includes(timelineFitZoom(900, width) as typeof PIXEL_BGR_TIMELINE_ZOOM_LEVELS[number]), "every Fit result belongs to the canonical preset list");
}
const emptyScene = { ...desert, tracks: [], events: [] };
const emptyProjection = projectBackgroundV2Timeline(emptyScene, {}, 0);
assert.deepEqual(emptyProjection.bounds, { startX: 0, endX: 0 }, "an empty authored scene has safe zero-width bounds");
assert.equal(timelineFitZoom(900, Math.max(720, emptyProjection.bounds.endX - emptyProjection.bounds.startX)), 1, "an empty authored scene fits safely");
const sceneWithFarEvent = { ...emptyScene, events: [{ id: "far", type: "signal" as const, worldX: 50_000, enabled: true, name: "far" }] };
const sceneBeforeFit = structuredClone(sceneWithFarEvent);
const eventProjection = projectBackgroundV2Timeline(sceneWithFarEvent, {}, 123);
assert.equal(eventProjection.bounds.endX, 50_000, "the farthest Event expands the authored fit range");
assert.equal(timelineFitZoom(900, Math.max(720, eventProjection.bounds.endX - eventProjection.bounds.startX)), 0.015, "the farther Event changes Fit to the required smaller preset");
assert.equal(eventProjection.playerX, 123, "deriving Fit bounds does not seek Player X");
assert.deepEqual(sceneWithFarEvent, sceneBeforeFit, "deriving Fit bounds does not mutate scene data");

assert.match(source, /private v2TimelineZoom = 0\.1/, "presentation zoom defaults to the practical 1:10 overview");
assert.match(source, /createExactTimelineScale\([^;]*this\.v2TimelineZoom\)/, "ruler, cursor, seek, drag and resize receive one zoomed scale");
assert.match(source, /cursorViewportX[\s\S]*this\.v2TimelineZoom=next;this\.render\(\)[\s\S]*newScroll\.scrollLeft/, "zoom preserves Player X's viewport position without seeking");
assert.match(source, /zoomControls\.append\(zoomOut,fit,zoomIn\)/, "Fit is visible between zoom out and zoom in");
assert.match(source, /timelineScroll=this\.workspace\.timeline\.querySelector[\s\S]*viewportWidth=timelineScroll\?\.clientWidth\?\?this\.workspace\.timeline\.clientWidth[\s\S]*availableWidth=Math\.max\(1,viewportWidth-fitPaddingPx\)[\s\S]*timelineFitZoom\(availableWidth,baseWidthPx\)/, "Fit uses the actual scroll viewport once, with only compact padding");
assert(timelineFitZoom(900 - 24, 1_000) >= 0.75, "Fit uses most of the available viewport when a closer discrete preset fits");
assert.match(source, /currentIndex=PIXEL_BGR_TIMELINE_ZOOM_LEVELS\.indexOf[\s\S]*currentIndex\+direction/, "minus and plus step only through the canonical preset list");
const fitMethod = source.slice(source.indexOf("private fitV2Timeline"), source.indexOf("private changeV2TimelineZoom"));
assert.doesNotMatch(fitMethod, /v2Selected|setCurrentX|setBackgroundSceneV2/, "Fit changes neither selection, Player X, nor scene data");
assert.doesNotMatch(source.slice(source.indexOf("private changeV2TimelineZoom"), source.indexOf("private openV2EventInsertMenu")), /setCurrentX|setBackgroundSceneV2/, "zoom mutates neither Player X nor scene data");
assert.match(source, /eye\.onpointerdown=isolateTimelinePointerEvent/, "eye pointerdown uses timeline pointer isolation");
assert.match(source, /visibility!=="all"/, "mixed and disabled lanes deterministically enable all on click");
assert.match(source, /gutterRow\.append\(label,parallax,eye,add\)/, "each compact gutter row uses label, parallax, eye, add order");
assert.equal((source.match(/for\(const lane of projection\.lanes\)/g) ?? []).length >= 2, true, "all four projected role lanes receive gutter controls and timeline rows");
assert.match(source, /this\.workspace\.gutter\.appendChild\(gutter\)/, "fixed gutter is mounted in the left workspace region");
assert.match(source, /panel\.appendChild\(scroll\)/, "timeline lanes remain in the center horizontal scroll owner");
assert.match(layout, /grid-template-rows: minmax\(0, 1fr\) 176px/, "center timeline allocation remains 176px");
assert.match(layout, /\.cm-bgr-workspace-timeline \{[\s\S]*?overflow-x: hidden;[\s\S]*?overflow-y: hidden;/, "outer center timeline retains no vertical scrollbar");
console.log("[SMOKE] PixelBgrMultitrackControls OK ✅");
