import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { v2YRailValue } from "./PixelBgrV2YRail";

const drag={pointerId:1,startClientY:100,originalY:-20,logicPerClientPx:2};
assert.equal(v2YRailValue(drag,110),0);
assert.equal(v2YRailValue(drag,90),-40);
assert.equal(v2YRailValue(drag,10000),19780,"rail is not canonically bounded");

const source=readFileSync(new URL("./PixelBgrLabUI.ts",import.meta.url),"utf8");
const method=(name:string,next:string)=>source.slice(source.indexOf(`private ${name}`),source.indexOf(`private ${next}`));
assert.doesNotMatch(method("selectV2Event","selectV2Track"),/v2SelectedSegmentId|v2SelectedObjectId/,"Event selection preserves visual selection");
assert.doesNotMatch(method("selectV2Segment","selectV2Object"),/v2SelectedEventId/,"segment selection preserves Event selection");
assert.doesNotMatch(method("selectV2Object","renderV2EventSurface"),/v2SelectedEventId/,"object selection preserves Event selection");
assert.match(source,/panel\.append\(contextualY,this\.renderV2YRail\(\),scroll\)/,"the readout, rail, and timeline are always mounted in visual order");
assert.doesNotMatch(source,/has-y-rail/,"selection does not control layout width");
assert.match(source,/\.cm-v2-panel\{[^}]*display:grid;grid-template-columns:42px 21px minmax\(0,1fr\)/,"the permanent grid reserves readout and rail columns");
assert.match(source,/\.cm-v2-panel \.cm-v2-timeline-scroll\{grid-column:3;grid-row:1;width:auto;min-width:0\}/,"timeline geometry is fixed in the third column");
assert.match(source,/\.cm-v2-panel \.cm-v2-selected-y\{grid-column:1;/,"the readout is structurally left of the rail");
assert.match(source,/\.cm-v2-panel \.cm-v2-y-rail\{grid-column:2\}/,"the rail stays adjacent to the timeline");
assert.match(source,/surface\.dataset\.contextualY="neutral";readout\.textContent="Y —"/,"no visual selection has a neutral readout");
assert.match(source,/rail\.setAttribute\("aria-disabled",String\(!hasVisualSelection\)\)/,"the neutral rail is disabled");
assert.match(source,/const thumb=hasVisualSelection\?el\("span","cm-v2-y-rail-thumb"\):null/,"the thumb only exists for visual selection");
assert.match(source,/surface\.dataset\.contextKind=segment\?"segment":"object"/,"segment and object selections own Y");
assert.match(source,/if\(contextualY\.dataset\.contextKind\)panel\.dataset\.contextKind=contextualY\.dataset\.contextKind/,"Event plus visual selection preserves visual Y ownership");
assert.match(source,/if\(!segment&&!object\)return;/,"the neutral rail cannot begin a drag");
assert.match(source,/this\.workspace\.timeline\.appendChild\(this\.renderV2Timeline\(projection\)\)/,"the complete stable panel stays in the center-owned timeline workspace");
assert.match(source,/width:21px;min-height:155px;background:/,"rail has a persistent visible interaction surface");
assert.match(source,/width:21px;height:21px/,"the active rail thumb remains visible");
assert.match(source,/drag\.thumb\?\.style\.setProperty\("transform"/,"rail thumb tracks pointer movement");
assert.match(source,/\{offsetY:y\}/);assert.match(source,/\{y\}\)/);
console.log("[SMOKE] PixelBgrV2YRail OK ✅");
