import assert from "node:assert/strict";
import { createDemoScene, addMarker, duplicateMarker, deleteMarker, moveMarker, toggleMarker, markerOwner, updateMarker, addMarkerAction, updateMarkerAction, duplicateMarkerAction, moveMarkerAction, deleteMarkerAction } from "./PixelBgrLabState";
import { exportBackgroundScene, importBackgroundSceneJson } from "./PixelBgrLabSerialization";
import { validateBackgroundScene } from "./PixelBgrLabValidation";
import { PIXEL_BGR_LAB_TABS } from "./PixelBgrLabUI";

let scene = createDemoScene();
assert.equal(PIXEL_BGR_LAB_TABS.includes("markers" as any), true);
assert.ok(scene.markers?.length);
const before = JSON.stringify(scene);
scene = addMarker(scene, { kind: "global" });
assert.equal(markerOwner(scene, { kind: "global" }).at(-1)?.id, "marker");
scene = duplicateMarker(scene, { kind: "global" }, "marker");
assert.equal(markerOwner(scene, { kind: "global" }).some(m => m.id === "marker-copy"), true);
scene = moveMarker(scene, { kind: "global" }, "marker-copy", -1);
scene = toggleMarker(scene, { kind: "global" }, "marker-copy");
assert.equal(markerOwner(scene, { kind: "global" }).find(m=>m.id==="marker-copy")?.enabled, false);
scene = updateMarker(scene, { kind: "global" }, "marker-copy", m => ({ ...m, x: 64, once: false }));
scene = addMarkerAction(scene, { kind: "global" }, "marker-copy");
scene = updateMarkerAction(scene, { kind: "global" }, "marker-copy", 0, () => ({ kind: "emit-environment-event", event: "test" }));
scene = duplicateMarkerAction(scene, { kind: "global" }, "marker-copy", 0);
scene = moveMarkerAction(scene, { kind: "global" }, "marker-copy", 1, -1);
scene = deleteMarkerAction(scene, { kind: "global" }, "marker-copy", 1);
assert.equal(markerOwner(scene, { kind: "global" }).find(m=>m.id==="marker-copy")?.actions.length, 1);
scene = deleteMarker(scene, { kind: "global" }, "marker-copy");
assert.equal(markerOwner(scene, { kind: "global" }).some(m => m.id === "marker-copy"), false);
assert.notEqual(JSON.stringify(scene), before);
const round = importBackgroundSceneJson(exportBackgroundScene(scene));
assert.equal(round.ok, true);
assert.ok((round as any).scene.markers?.length);
const old = { id: "old", globalLayers: [], chunks: [] };
assert.equal(importBackgroundSceneJson(JSON.stringify(old)).ok, true);
const bad = structuredClone(scene) as any;
bad.markers = [{ id: "dup", x: 1, enabled: true, once: true, actions: [] }, { id: "dup", x: 2, enabled: true, once: true, actions: [] }];
assert.equal(validateBackgroundScene(bad).valid, false);
bad.markers = [{ id: "m", x: 1, enabled: true, once: true, actions: [{ kind: "pulse-layer-opacity", layerId: "global:nope", from: 0, to: 1, durationMs: 0 }] }];
assert.equal(validateBackgroundScene(bad).valid, false);
assert.equal(validateBackgroundScene(bad).warnings.some(w => w.message.includes("target layer currently unavailable")), true);
console.log("PixelBgrLabB5.smoke passed");
