import assert from "node:assert/strict";
import { evaluateBackgroundScene } from "../render/bg/v2/BackgroundV2Evaluator";
import { parseBackgroundSceneV2, serializeBackgroundSceneV2 } from "../render/bg/v2/BackgroundV2Serialization";
import type { BackgroundSceneV2 } from "../render/bg/v2/BackgroundV2Types";
import { materializeBackgroundFrameCommands } from "../render/webgl/bg/v2/BackgroundV2RenderCommands";
import { duplicateV2Object, moveV2Object, updateV2Object } from "./PixelBgrV2ObjectEditing";
import { applyV2SegmentDrag, duplicateV2Segment, updateV2Segment } from "./PixelBgrV2SegmentEditing";
import { deleteV2SceneEvent, duplicateV2SceneEvent, updateV2SceneEvent } from "./PixelBgrV2SceneEvents";
import { nudgeV2SelectionY } from "./PixelBgrV2YNudge";
import { v2EntityDisplayName } from "./PixelBgrV2EntityDisplayName";
import fs from "node:fs";

const scene: BackgroundSceneV2={version:2,id:"entity-model",environment:{},tracks:[{id:"track",name:"Track",role:"mid",mode:"sequence",enabled:true,parallax:{x:1,y:1},zBase:0,segments:[{id:"seg",name:"Clouds",locked:true,flipX:true,flipY:true,startTrackX:10,widthPx:40,asset:{id:"cloud",url:"/cloud.png"},offsetY:20,opacity:1,blend:"normal",localZ:0,enabled:true}],objects:[{id:"obj",name:"Moon",locked:true,flipX:true,flipY:true,asset:{id:"moon",url:"/moon.png"},startTrackX:80,y:30,width:20,height:25,localZ:1,opacity:1,blend:"normal",enabled:true}]}],events:[{id:"end",type:"level-end",name:"Finish",worldX:200,enabled:true,locked:true},{id:"eve",type:"signal",name:"Pulse",worldX:100,enabled:true}]};
const json=serializeBackgroundSceneV2(scene);const parsed=parseBackgroundSceneV2(json);assert.equal(parsed.ok,true);if(!parsed.ok)throw Error(parsed.error);assert.deepEqual(parsed.scene,scene,"serialization preserves additive authoring metadata");
const frame=evaluateBackgroundScene(scene,{playerWorldX:0,cameraScrollX:0,cameraScrollY:0,viewportWidth:896,viewportHeight:504});assert.equal(frame.behindGameplay.length,2,"runtime does not hide locked entities");assert.equal("locked" in frame.behindGameplay[0],false,"runtime instances ignore lock metadata");
const commands=materializeBackgroundFrameCommands(frame,{playerWorldX:0}).behindGameplay;assert.deepEqual(commands.map(({flipX,flipY})=>[flipX,flipY]),[[true,true],[true,true]],"renderer commands receive flip state");assert.deepEqual(commands.map(({x,y,width,height})=>[x,y,width,height]),[[10,20,40,undefined],[80,30,20,25]],"flip preserves geometry and ordering");
assert.equal(applyV2SegmentDrag(scene,"track","seg","move",16).ok,false);assert.equal(moveV2Object(scene,"track","obj",90,40).ok,false);assert.equal(nudgeV2SelectionY(scene,"track","seg","",1),null);assert.equal(nudgeV2SelectionY(scene,"track","","obj",1),null);assert.equal(updateV2SceneEvent(scene,"end",{worldX:216}).ok,false);assert.equal(duplicateV2SceneEvent(scene,"end").ok,false);assert.equal(deleteV2SceneEvent(scene,"end").ok,false);
const unlockedSeg=updateV2Segment(scene,"track","seg",{locked:false});assert(unlockedSeg.ok);if(unlockedSeg.ok){const duplicate=duplicateV2Segment(unlockedSeg.scene,"track","seg");assert(duplicate.ok);if(duplicate.ok)assert.equal(duplicate.scene.tracks[0].segments[1].locked,false);}
const unlockedObj=updateV2Object(scene,"track","obj",{locked:false});assert(unlockedObj.ok);if(unlockedObj.ok){const duplicate=duplicateV2Object(unlockedObj.scene,"track","obj");assert(duplicate.ok);if(duplicate.ok)assert.equal(duplicate.scene.tracks[0].objects[1].locked,false);}
const renamed=updateV2Object(unlockedObj.ok?unlockedObj.scene:scene,"track","obj",{name:"New Moon"});assert(renamed.ok);if(renamed.ok){assert.equal(renamed.scene.tracks[0].objects[0].id,"obj");assert.equal(renamed.scene.tracks[0].objects[0].name,"New Moon");}
const ui=fs.readFileSync(new URL("./PixelBgrLabUI.ts",import.meta.url),"utf8");for(const command of ["Lock","Unlock","Duplicate","Flip Horizontal","Flip Vertical","Rename","Delete"])assert(ui.includes(command),`missing menu command ${command}`);assert.match(ui,/openV2EventContextMenu[\s\S]*?Duplicate[\s\S]*?Rename[\s\S]*?Delete/);assert.doesNotMatch(ui.slice(ui.indexOf("private openV2EventContextMenu"),ui.indexOf("private applyV2EventEdit")),/Flip Horizontal|Flip Vertical/);assert(!ui.includes("openV2LayerContextMenu"));assert.equal(v2EntityDisplayName({id:"fallback",name:"  "}),"fallback");assert.equal(v2EntityDisplayName({id:"id",name:"  Display  "}),"Display");assert.match(ui,/this\.v2SelectedEventId=eventId/);assert.match(ui,/this\.v2SelectedTrackId=trackId/);
console.log("PixelBgrV2EntityModel smoke passed");
