import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import type { BackgroundSceneV2 } from "../render/bg/v2/BackgroundV2Types";
import { updateV2Object } from "./PixelBgrV2ObjectEditing";
import { updateV2Segment } from "./PixelBgrV2SegmentEditing";
const asset={id:"a",url:"/a.png"};
const scene:BackgroundSceneV2={version:2,id:"context-y",environment:{},tracks:[{id:"mid",name:"Mid",role:"mid",mode:"sequence",enabled:true,parallax:{x:.3,y:.3},zBase:0,segments:[{id:"mid-a",startTrackX:0,widthPx:20,asset,offsetY:-55,opacity:1,blend:"normal",localZ:0,enabled:true}],objects:[{id:"rock",asset,startTrackX:30,y:12,localZ:0,opacity:1,blend:"normal",enabled:true}]}]};
const segment=updateV2Segment(scene,"mid","mid-a",{offsetY:-56});assert(segment.ok);if(segment.ok)assert.equal(segment.scene.tracks[0].segments[0].offsetY,-56);
const object=updateV2Object(scene,"mid","rock",{y:13});assert(object.ok);if(object.ok)assert.equal(object.scene.tracks[0].objects[0].y,13);
const source=readFileSync(new URL("./PixelBgrLabUI.ts",import.meta.url),"utf8");
assert.match(source,/panel\.append\(contextualY,this\.renderV2YRail\(\),scroll\)/,"Y controls mount in visual order in the timeline panel");
assert.doesNotMatch(source,/workspace\.left\.appendChild\(this\.renderV2YRail/);
assert.match(source,/const value=segment\?\.segment\.offsetY\?\?object!\.object\.y/);
assert.match(source,/readout\.textContent=`Y \${Math\.round\(value\)}`/);
assert.doesNotMatch(source.slice(source.indexOf("private renderV2ContextualYSurface"),source.indexOf("private renderV2YRail")),/numericStepper|cm-pixel-stepper/,"no permanent Y stepper remains beside the timeline");
console.log("[SMOKE] PixelBgrV2ContextualYSurface OK ✅");
