import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import type { BackgroundSceneV2 } from "../render/bg/v2/BackgroundV2Types";
import { nudgeV2SelectionY } from "./PixelBgrV2YNudge";
const asset={id:"a",url:"/a.png"};const scene:BackgroundSceneV2={version:2,id:"y",environment:{},tracks:[{id:"far",name:"Far",role:"far",mode:"sequence",enabled:true,parallax:{x:1,y:1},zBase:0,segments:[{id:"s",startTrackX:0,widthPx:20,asset,offsetY:-55,opacity:1,blend:"normal",localZ:0,enabled:true}],objects:[{id:"o",asset,startTrackX:0,y:175,localZ:0,opacity:1,blend:"normal",enabled:true}]}]};
const original=structuredClone(scene);const segment=nudgeV2SelectionY(scene,"far","s","",-1);assert(segment?.ok);if(segment?.ok)assert.equal(segment.scene.tracks[0].segments[0].offsetY,-56);const segmentShift=nudgeV2SelectionY(scene,"far","s","",10);assert(segmentShift?.ok);if(segmentShift?.ok)assert.equal(segmentShift.scene.tracks[0].segments[0].offsetY,-45);const object=nudgeV2SelectionY(scene,"far","","o",1);assert(object?.ok);if(object?.ok)assert.equal(object.scene.tracks[0].objects[0].y,176);const objectShift=nudgeV2SelectionY(scene,"far","","o",-10);assert(objectShift?.ok);if(objectShift?.ok)assert.equal(objectShift.scene.tracks[0].objects[0].y,165);assert.deepEqual(scene,original);assert.deepEqual(Object.keys(segment!.scene.tracks[0].segments[0]).sort(),Object.keys(scene.tracks[0].segments[0]).sort(),"segment schema is unchanged");
const source=readFileSync(new URL("./PixelBgrLabUI.ts",import.meta.url),"utf8");assert.match(source,/this\.row\("Y",this\.numericStepper\(\{value:selected\.segment\.offsetY/);assert.match(source,/this\.row\("Y",this\.numericStepper\(\{value:object\.y/);assert.match(source,/isV2YNudgeTextTarget\(e\.target\)/);assert.match(source,/e\.shiftKey\?10:1/);assert.match(source,/if\(!result\)return;e\.preventDefault\(\)/);
const nudgeSource=readFileSync(new URL("./PixelBgrV2YNudge.ts",import.meta.url),"utf8");for(const tag of ["input","textarea","select","[contenteditable]"])assert(nudgeSource.includes(tag));
console.log("[SMOKE] PixelBgrV2YNudge OK ✅");
