import { strict as assert } from "node:assert";
import type { BackgroundSceneV2 } from "../render/bg/v2/BackgroundV2Types";
import { bindEventAction, bindTriggerEvent, createAction, createSceneEvent, createSpaceTrigger, createStateReference, createStateTrigger, createTimeTrigger, deleteAction, deleteSceneEvent, deleteStateReference, deleteTrigger, unbindEventAction, unbindTriggerEvent, updateSceneEvent, updateTrigger } from "./SceneLogicEditing";
import { createMarker, createRange, createZone } from "./SceneLogicSpaceEditing";
const base:BackgroundSceneV2={version:2,id:"logic",environment:{},tracks:[],events:[]};
let scene=createMarker(base,-1703.8);assert(scene.ok);scene=createRange(scene.scene,10,20);assert(scene.ok);scene=createZone(scene.scene,30,100,40);assert(scene.ok);let current=scene.scene;
for(const [kind,id,relation] of [["marker","marker_1","cross"],["range","range_1","inside"],["zone","zone_1","exit"]] as const){const r=createSpaceTrigger(current,kind,id,relation);assert(r.ok);current=r.scene;}
let result=createTimeTrigger(current,"after");assert(result.ok);current=result.scene;result=createStateReference(current,"state_scroll_speed");assert(result.ok);current=result.scene;result=createStateReference(current,"state_player_alive");assert(result.ok);current=result.scene;assert(!createStateReference(current,"arbitrary").ok);result=createStateTrigger(current,"state_scroll_speed",">");assert(result.ok);current=result.scene;
assert.deepEqual(current.sceneLogic!.triggers.map(x=>x.id),["trigger_1","trigger_2","trigger_3","trigger_4","trigger_5"]);result=updateTrigger(current,"trigger_1",{enabled:false,mode:"repeat"});assert(result.ok);current=result.scene;assert(!createSpaceTrigger(current,"marker","missing").ok);
result=createSceneEvent(current,"boss_encounter_started");assert(result.ok);current=result.scene;assert(!updateSceneEvent(current,"event_1","").ok);result=updateSceneEvent(current,"event_1","boss_started");assert(result.ok);current=result.scene;
for(const draft of [{category:"world",type:"stop_scroll"},{category:"state",type:"set",stateId:"state_player_alive",value:true},{category:"state",type:"increment",stateId:"state_scroll_speed",value:1},{category:"state",type:"decrement",stateId:"state_scroll_speed",value:1},{category:"flow",type:"restart_level"}] as const){result=createAction(current,draft);assert(result.ok);current=result.scene;}assert(!createAction(current,{category:"state",type:"increment",stateId:"state_player_alive",value:1}).ok);
result=bindTriggerEvent(current,"trigger_1","event_1");assert(result.ok);current=result.scene;assert(!bindTriggerEvent(current,"trigger_1","event_1").ok);assert(!bindTriggerEvent(current,"missing","event_1").ok);result=bindEventAction(current,"event_1","action_1");assert(result.ok);current=result.scene;assert(!bindEventAction(current,"event_1","action_1").ok);assert(!deleteTrigger(current,"trigger_1").ok);assert(!deleteSceneEvent(current,"event_1").ok);assert(!deleteAction(current,"action_1").ok);assert(!deleteStateReference(current,"state_scroll_speed").ok);
result=unbindTriggerEvent(current,"trigger_1","event_1");assert(result.ok);current=result.scene;result=unbindEventAction(current,"event_1","action_1");assert(result.ok);current=result.scene;assert(deleteSceneEvent(current,"event_1").ok);assert(deleteAction(current,"action_1").ok);
assert.equal(current.sceneLogic!.spaces.markers[0].position,-1703.8);console.log("Scene Logic editing smoke passed");
