import { strict as assert } from "node:assert";
import type { BackgroundSceneV2 } from "../render/bg/v2/BackgroundV2Types";
import { bindEventAction, bindTriggerEvent, createAction, createSceneEvent, createSpaceTrigger, createStateReference, createStateTrigger, createTimeTrigger, deleteAction, deleteSceneEvent, deleteStateReference, deleteTrigger, unbindEventAction, unbindTriggerEvent, stateActionReferencePatch, stateActionStates, stateTriggerReferencePatch, stateTriggerRelations, updateAction, updateSceneEvent, updateTrigger } from "./SceneLogicEditing";
import { createMarker, createRange, createZone } from "./SceneLogicSpaceEditing";
const base:BackgroundSceneV2={version:2,id:"logic",environment:{},tracks:[],events:[]};
let scene=createMarker(base,-1703.8);assert(scene.ok);scene=createRange(scene.scene,10,20);assert(scene.ok);scene=createRange(scene.scene,21,29);assert(scene.ok);scene=createZone(scene.scene,30,100,40);assert(scene.ok);scene=createZone(scene.scene,41,100,50);assert(scene.ok);let current=scene.scene;
for(const [kind,id,relation] of [["marker","marker_1","cross"],["range","range_1","enter"],["zone","zone_1","enter"]] as const){const r=createSpaceTrigger(current,kind,id,relation);assert(r.ok);current=r.scene;}
let result=createTimeTrigger(current,"after");assert(result.ok);current=result.scene;result=createStateReference(current,"state_scroll_speed");assert(result.ok);current=result.scene;result=createStateReference(current,"state_player_alive");assert(result.ok);current=result.scene;assert(!createStateReference(current,"arbitrary").ok);result=createStateTrigger(current,"state_scroll_speed",">");assert(result.ok);current=result.scene;
assert.deepEqual(current.sceneLogic!.triggers.map(x=>x.id),["trigger_1","trigger_2","trigger_3","trigger_4","trigger_5"]);
let rangeEdit=updateTrigger(current,"trigger_2",{relation:"inside"});assert(rangeEdit.ok);rangeEdit=updateTrigger(rangeEdit.scene,"trigger_2",{relation:"exit",rangeId:"range_2"});assert(rangeEdit.ok);current=rangeEdit.scene;const editedRange=current.sceneLogic!.triggers[1];assert("rangeId" in editedRange&&editedRange.rangeId==="range_2"&&editedRange.relation==="exit");
let zoneEdit=updateTrigger(current,"trigger_3",{relation:"inside"});assert(zoneEdit.ok);zoneEdit=updateTrigger(zoneEdit.scene,"trigger_3",{relation:"exit",zoneId:"zone_2"});assert(zoneEdit.ok);current=zoneEdit.scene;const editedZone=current.sceneLogic!.triggers[2];assert("zoneId" in editedZone&&editedZone.zoneId==="zone_2"&&editedZone.relation==="exit");
assert.deepEqual(stateTriggerRelations("number"),["==","!=","<","<=",">",">="]);assert.deepEqual(stateTriggerRelations("boolean"),["==","!="]);const booleanState=current.sceneLogic!.states.find(x=>x.id==="state_player_alive")!;const normalized=stateTriggerReferencePatch(booleanState,">",12);assert.deepEqual(normalized,{stateId:"state_player_alive",relation:"==",value:false});result=updateTrigger(current,"trigger_5",normalized);assert(result.ok);current=result.scene;
result=updateTrigger(current,"trigger_1",{enabled:false,mode:"repeat"});assert(result.ok);current=result.scene;assert(!createSpaceTrigger(current,"marker","missing").ok);
result=createSceneEvent(current,"boss_encounter_started");assert(result.ok);current=result.scene;assert(!updateSceneEvent(current,"event_1","").ok);result=updateSceneEvent(current,"event_1","boss_started");assert(result.ok);current=result.scene;
for(const draft of [{category:"world",type:"stop_scroll"},{category:"state",type:"set",stateId:"state_player_alive",value:true},{category:"state",type:"increment",stateId:"state_scroll_speed",value:1},{category:"state",type:"decrement",stateId:"state_scroll_speed",value:1},{category:"flow",type:"restart_level"}] as const){result=createAction(current,draft);assert(result.ok);current=result.scene;}assert(!createAction(current,{category:"state",type:"increment",stateId:"state_player_alive",value:1}).ok);
const numberState=current.sceneLogic!.states.find(x=>x.id==="state_scroll_speed")!;assert.deepEqual(stateActionStates("increment",current.sceneLogic!.states).map(x=>x.id),["state_scroll_speed"]);const setPatch=stateActionReferencePatch("set",numberState,true);assert.deepEqual(setPatch,{stateId:"state_scroll_speed",value:0});result=updateAction(current,"action_2",setPatch);assert(result.ok);current=result.scene;result=updateAction(current,"action_2",{value:5});assert(result.ok);current=result.scene;result=updateAction(current,"action_3",{value:5});assert(result.ok);current=result.scene;result=updateAction(current,"action_4",{value:2});assert(result.ok);current=result.scene;assert.deepEqual(current.sceneLogic!.actions.slice(1,4).map(action=>[action.id,"value" in action?action.value:null]),[["action_2",5],["action_3",5],["action_4",2]]);assert(!updateAction(current,"action_3",{stateId:"state_player_alive"}).ok);assert(!updateAction(current,"action_3",{value:Number.POSITIVE_INFINITY}).ok);assert.equal(current.sceneLogic!.actions[2].id,"action_3");
result=bindTriggerEvent(current,"trigger_1","event_1");assert(result.ok);current=result.scene;assert(!bindTriggerEvent(current,"trigger_1","event_1").ok);assert(!bindTriggerEvent(current,"missing","event_1").ok);result=bindEventAction(current,"event_1","action_1");assert(result.ok);current=result.scene;assert(!bindEventAction(current,"event_1","action_1").ok);assert(!deleteTrigger(current,"trigger_1").ok);assert(!deleteSceneEvent(current,"event_1").ok);assert(!deleteAction(current,"action_1").ok);assert(!deleteStateReference(current,"state_scroll_speed").ok);
result=unbindTriggerEvent(current,"trigger_1","event_1");assert(result.ok);current=result.scene;result=unbindEventAction(current,"event_1","action_1");assert(result.ok);current=result.scene;assert(deleteSceneEvent(current,"event_1").ok);assert(deleteAction(current,"action_1").ok);
assert.equal(current.sceneLogic!.spaces.markers[0].position,-1703.8);console.log("Scene Logic editing smoke passed");
