import assert from "node:assert/strict";
import { createB2BackgroundSceneDemoState } from "./BackgroundLayerTypes";
import { resolveBackgroundMarkers } from "./BackgroundMarkerResolve";
import { createBackgroundMarkerRuntime, evaluateBackgroundMarkerCrossings, resetBackgroundMarkerRuntime } from "./BackgroundMarkerRuntime";
import { applyBackgroundMarkerActions, applyBackgroundPresentationOverrides, createBackgroundPresentationOverrides, stepBackgroundPresentationOverrides } from "./BackgroundPresentationOverrides";
import { composeBackgroundLayers, resolveActiveBackgroundChunks } from "./BackgroundSceneResolve";

const scene = (createB2BackgroundSceneDemoState().source as any).scene;
const markers = resolveBackgroundMarkers(scene);
assert.equal(markers[0].runtimeId, "global-marker:global-star-pulse");
assert.equal(markers[0].worldX, 180);
assert.equal(markers.some(m => m.runtimeId === "chunk-marker:chunk-a:disable-near-rocks" && m.worldX === 220), true);
assert.equal(markers.some(m => m.runtimeId === "chunk-marker:chunk-b:enter" && m.worldX === 800), true);
const ids = markers.map(m => m.runtimeId);
assert.deepEqual(ids, [...ids].sort((a,b)=>markers.find(m=>m.runtimeId===a)!.worldX-markers.find(m=>m.runtimeId===b)!.worldX || a.localeCompare(b)).slice(0, ids.length));
const before = JSON.stringify(scene);
const rt = createBackgroundMarkerRuntime();
assert.deepEqual(evaluateBackgroundMarkerCrossings(rt, scene.id, 300, markers).map(m=>m.runtimeId), []);
assert.deepEqual(evaluateBackgroundMarkerCrossings(rt, scene.id, 350, markers).map(m=>m.runtimeId), []);
resetBackgroundMarkerRuntime(rt);
assert.deepEqual(evaluateBackgroundMarkerCrossings(rt, scene.id, 0, markers), []);
assert.deepEqual(evaluateBackgroundMarkerCrossings(rt, scene.id, 180, markers).map(m=>m.runtimeId), ["global-marker:global-star-pulse"]);
assert.deepEqual(evaluateBackgroundMarkerCrossings(rt, scene.id, 900, markers).map(m=>m.runtimeId), ["chunk-marker:chunk-a:disable-near-rocks", "chunk-marker:chunk-b:enter"]);
assert.deepEqual(evaluateBackgroundMarkerCrossings(rt, scene.id, 1000, markers), []);
assert.deepEqual(evaluateBackgroundMarkerCrossings(rt, scene.id, 700, markers), []);
assert.deepEqual(evaluateBackgroundMarkerCrossings(rt, scene.id, 801, markers).map(m=>m.runtimeId), ["chunk-marker:chunk-b:enter"]);
assert.deepEqual(evaluateBackgroundMarkerCrossings(rt, "new-scene", 900, markers), []);
assert.equal(JSON.stringify(scene), before);

let layers = composeBackgroundLayers(scene, resolveActiveBackgroundChunks(scene, 0, 896));
const overrides = createBackgroundPresentationOverrides();
const layerIds = new Set(layers.map(l => l.id));
applyBackgroundMarkerActions(overrides, markers[0], scene.id, 0, layerIds);
stepBackgroundPresentationOverrides(overrides, 250);
layers = applyBackgroundPresentationOverrides(layers, overrides);
assert.equal((layers.find(l=>l.id==="global:far-stars") as any).opacity, 0.625);
stepBackgroundPresentationOverrides(overrides, 250);
layers = applyBackgroundPresentationOverrides(layers, overrides);
assert.equal((layers.find(l=>l.id==="global:far-stars") as any).opacity, 1);
const disable = markers.find(m=>m.runtimeId==="chunk-marker:chunk-a:disable-near-rocks")!;
applyBackgroundMarkerActions(overrides, disable, scene.id, 500, layerIds);
layers = applyBackgroundPresentationOverrides(composeBackgroundLayers(scene, resolveActiveBackgroundChunks(scene, 0, 896)), overrides);
assert.equal(layers.find(l=>l.id==="chunk:chunk-a:near-rocks")?.enabled, false);
const event = markers.find(m=>m.runtimeId==="chunk-marker:chunk-b:enter")!;
applyBackgroundMarkerActions(overrides, event, scene.id, 800, new Set(composeBackgroundLayers(scene, resolveActiveBackgroundChunks(scene, 720, 896)).map(l=>l.id)));
assert.equal(overrides.lastEnvironmentEvent?.name, "chunk-b-enter");
console.log("BackgroundMarkers.smoke passed");
