import assert from "node:assert/strict";
import { EntityStore } from "../engine/ecs/EntityStore";
import { SpawnSystem } from "../game/systems/SpawnSystem";
import { WEAPONS_MVP } from "../game/defs/Weapons";
import { CONTENT } from "../game/content/CONTENT";
import { FsmPreviewSession } from "./FsmPreviewSession";

const store = new EntityStore<any>(32);
const world = { scrollX: 0, scrollY: 0 } as any;
const spawn = new SpawnSystem(store, { rng01: () => 0.5, logicSize: { w: 896, h: 504 }, weaponDb: WEAPONS_MVP as any }, world);
let tick = 1;
const session = new FsmPreviewSession({ store, spawnPreviewEnemy: (p) => spawn.spawnPreviewEnemy(p as any), getTick: () => tick, previewX: 700, previewY: 111 });
const persisted = CONTENT.fsmPresets.list()[0];
let s = session.startPersistedPreview(persisted.id);
assert.equal(s.status, "running");
assert.equal(s.source, "persisted");
assert.equal(s.position?.x, 700);
assert.equal(s.position?.y, 111);
const first = s.entityRef!;
s = session.startDraftPreview(persisted.definition as any, true);
assert.equal(s.status, "running");
assert.equal(store.get(first)?.pendingKill, true, "new preview marks previous preview for cleanup");
assert.equal(s.source, "draft");
const second = s.entityRef!;
s = session.restart();
assert.equal(s.status, "running");
assert.notDeepEqual(s.entityRef, second, "restart creates a fresh entity ref");
assert.equal(store.get(second)?.pendingKill, true, "restart stops old entity through markKill");
s = session.stop();
assert.equal(s.status, "ended");
assert.equal(store.get(s.entityRef!)?.pendingKill, true);
s = session.stop();
assert.equal(s.status, "ended", "repeated stop is safe");
store.cleanup();
assert.equal(store.get(s.entityRef!), null, "cleanup owns final removal");
assert(s.runtime, "ended snapshot is retained");
const unrelated = store.spawn((e) => { e.kind = "enemy"; e.pos = { x: 1, y: 2 }; e.pendingKill = false; });
session.startPersistedPreview(persisted.id);
assert.equal(store.get(unrelated)?.pendingKill, false, "unrelated enemies are unaffected");
console.log("FsmPreviewSession smoke passed");
