import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { CONTENT } from "../game/content/CONTENT";
import { createUserFsmPresetStore, type KeyValueStorage } from "../game/enemies/fsm";
import { FsmPresetAuthoringModel } from "./FsmPresetAuthoringModel";
import { FsmPresetEditorModel } from "./FsmPresetEditorModel";

class MemoryStorage implements KeyValueStorage { data = new Map<string, string>(); getItem(k: string) { return this.data.get(k) ?? null; } setItem(k: string, v: string) { this.data.set(k, v); } removeItem(k: string) { this.data.delete(k); } }

const source = readFileSync("src/dev/DevSummoner.ts", "utf8");
const toolbarBlock = source.slice(source.indexOf('const topNewBtn = makeIconBtn'), source.indexOf('fsmPresetSection.appendChild(fsmSpawnSelect.root)'));
assert(toolbarBlock.includes('"New preset", "new"'), "New toolbar action is first");
assert(toolbarBlock.includes('"Edit preset name", "edit-name"'), "Edit-name toolbar action is second");
assert(toolbarBlock.includes('"Duplicate preset", "duplicate"'), "Duplicate toolbar action is third");
assert(toolbarBlock.includes('"Reset preset", "reset"'), "Reset toolbar action is fourth");
assert(toolbarBlock.includes('"Save preset", "save"'), "Save toolbar action is fifth");
assert(toolbarBlock.includes('"Delete preset", "delete"'), "Delete toolbar action is sixth");
assert(!toolbarBlock.includes('topImportBtn') && !toolbarBlock.includes('topRestartBtn') && !toolbarBlock.includes('ICONS.import'), "toolbar no longer mounts import/up-arrow or restart extras");
assert(source.includes('topDuplicateBtn.addEventListener("click"') && source.includes('presetModel.duplicate(); authoringModel = new FsmPresetAuthoringModel'), "Duplicate click is wired to duplicate and reload authoring model");
assert(source.includes('topResetBtn.addEventListener("click"') && source.includes('authoringModel.cancel(); presetModel.cancel();'), "Reset click discards draft edits");
assert(source.includes('topSaveBtn.addEventListener("click", (ev)') && source.includes('if (topSaveBtn.disabled) return; saveSelectedFsmPreset();'), "Save click is guarded and wired");

const store = createUserFsmPresetStore({ builtinRegistry: CONTENT.builtinFsmPresets, storage: new MemoryStorage(), knownMovementPresetIds: CONTENT.behaviorPresets.map((p) => p.id), nowIso: () => "2026-07-07T00:00:00.000Z" });
const model = new FsmPresetEditorModel(store);
const builtinId = CONTENT.builtinFsmPresets.list()[0]!.id;
assert.equal(model.select(builtinId).ok, true, "built-in selected");
const userCount0 = model.list().filter((x) => x.source === "user").length;
assert.equal(model.create().ok, true, "New creates a user preset");
assert.equal(model.list().filter((x) => x.source === "user").length, userCount0 + 1, "New adds exactly one user preset");
assert.equal(model.draft?.source, "user", "New selects editable user preset");
const newId = model.selectedId;
const beforeRenameGraph = JSON.stringify(store.get(newId)!.graph);
assert.equal(model.renameSelected("Toolbar Renamed").ok, true, "Edit name renames user preset");
assert.equal(model.selectedId, newId, "Edit name preserves ID");
assert.equal(JSON.stringify(store.get(newId)!.graph), beforeRenameGraph, "Edit name preserves FSM content");
assert.equal(model.select(builtinId).ok, true, "reselect built-in before duplicate");
assert.equal(model.duplicate().ok, true, "Duplicate works for built-in");
assert.equal(model.draft?.source, "user", "Duplicate selects new user preset");
assert.notEqual(model.selectedId, builtinId, "Duplicate gets new user ID");
const duplicateId = model.selectedId;
assert.deepEqual(store.get(duplicateId)!.graph, CONTENT.builtinFsmPresets.get(builtinId)!.definition.graph, "Duplicate deep-clones graph content");
const authoring = new FsmPresetAuthoringModel(store, duplicateId);
assert.equal(authoring.setPresetDescription("dirty draft").ok, true, "draft can be dirtied");
assert.equal(authoring.draft?.dirty, true, "draft dirty before reset");
assert.equal(authoring.cancel().ok, true, "Reset/cancel reloads saved preset");
assert.equal(authoring.draft?.dirty, false, "Reset clears dirty state");
assert.equal(authoring.setPresetDescription("saved draft").ok, true, "draft dirty before save");
assert.equal(authoring.save().ok, true, "Save persists user draft");
assert.equal(authoring.draft?.dirty, false, "Save clears dirty state");
assert.equal(store.get(duplicateId)?.metadata.description, "saved draft", "Save persists content");
const countBeforeCancelDelete = model.list().filter((x) => x.source === "user").length;
assert.equal(model.delete(duplicateId, false).ok, false, "Delete cancel is rejected by model");
assert.equal(model.list().filter((x) => x.source === "user").length, countBeforeCancelDelete, "Delete cancel preserves user presets");
assert.equal(model.delete(duplicateId, true).ok, true, "Delete confirm removes target");
assert.equal(store.get(duplicateId), undefined, "Delete removes only selected target");
assert(model.selectedId && CONTENT.fsmPresets.get(model.selectedId) || store.registry().get(model.selectedId), "Delete fallback selection is valid");
assert.equal(model.select(builtinId).ok, true, "built-in available");
assert.equal(model.renameSelected("Nope").ok, false, "built-in edit name unavailable");
assert.equal(model.save().ok, true, "built-in clean save is no-op");
assert.equal(model.delete(builtinId, true).ok, false, "built-in delete unavailable");
assert.equal(model.duplicate().ok, true, "built-in duplicate remains available");
console.log("[SMOKE] FsmPresetToolbarActions OK ✅");
