import { createAuthoring, assert } from "./FsmAuthoringSmokeHelpers";
import { FsmPresetAuthoringModel } from "./FsmPresetAuthoringModel";
import { CONTENT } from "../game/content/CONTENT";

const { store, model } = createAuthoring();
const persisted = store.get("user.s10")!;
model.setPresetLabel("Changed");
assert.equal(store.get("user.s10")!.metadata.name, persisted.metadata.name, "draft mutations do not affect store");
assert.equal(model.draft?.dirty, true);
assert.equal(model.canSave, true);
assert.equal(model.cancel().ok, true);
assert.equal(model.draft?.dirty, false);
model.setPresetDescription("description");
assert.equal(model.save().ok, true);
assert.equal(store.get("user.s10")!.metadata.description, "description");
model.deleteState("exit", true);
model.setInitialState("missing");
assert.equal(model.save().ok, false, "errors block save");
model.cancel();
model.addDespawnAction("idle");
assert(model.draft!.diagnostics.some((d) => d.severity === "warning"));
assert.equal(model.save().ok, true, "warnings allow save");
const builtin = new FsmPresetAuthoringModel(store, CONTENT.builtinFsmPresets.list()[0].id);
assert.equal(builtin.readOnly, true);
assert.equal(builtin.setPresetLabel("nope").ok, false);
assert.equal(model.requireDiscardConfirmation("other"), false);
model.setPresetLabel("Dirty again");
assert.equal(model.requireDiscardConfirmation("other"), true);
console.log("FsmPresetAuthoringModel smoke passed");
